name: Links

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build and export Next.js site
        run: |
          npx next build
          npx next export

      - name: Prepare site folder to match GitHub Pages basePath
        run: |
          mkdir -p site/webprofilebaim
          cp -r out/* site/webprofilebaim/

      - name: Start static server
        run: |
          # start a simple static server so absolute paths like /webprofilebaim/* resolve
          npx http-server site -p 8080 -c-1 &>/dev/null &
          sleep 1

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # point lychee at the served site; absolute paths will resolve under /webprofilebaim
          args: "--base http://localhost:8080 --cache --max-cache-age 1d site/webprofilebaim"
          fail: false

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
